#!/usr/bin/env bash
#
# Drishti in-place upgrade — safe, image-only roll.
#
#   curl -sL https://drishti.run/upgrade.sh | bash -s -- --region ap-southeast-2
#   curl -sL https://drishti.run/upgrade.sh | bash -s -- --region ap-southeast-2 --image-tag 0.2.0
#
# Rolls ONLY the App Runner service's image to the target version. The RDS instance is
# untouched, and the app runs its Flyway migrations on boot — so code AND schema upgrade
# with zero data loss. It deliberately does NOT re-run the install stack, which would
# stand up a fresh, empty database and lose every attestation and decision — the inputs
# that cannot be regenerated by re-scanning.
#
# Designed for AWS CloudShell, same as install.sh.
#
set -euo pipefail

REGION=""
STACK="drishti"
IMAGE_REPO="public.ecr.aws/w4o8p5x9/drishti"
TAG=""
# Version feed. drishti.run is the single source of truth (served fresh); the GitHub
# mirror is a fallback if the domain is unreachable.
VERSION_URLS=(
  "https://drishti.run/version.json"
  "https://raw.githubusercontent.com/abhijitsghosh/drishti-deploy/main/version.json"
)

# Ask EVERY feed and take the highest version. The feeds mirror the same release, so if
# one is a stale snapshot the other still reports the truth — first-wins would let a stale
# mirror pin you to an old version.
latest_version() {
  local url body ver best=""
  for url in "${VERSION_URLS[@]}"; do
    body="$(curl -fsSL "$url" 2>/dev/null)" || continue
    ver="$(printf '%s' "$body" | (jq -r '.latest' 2>/dev/null || sed -n 's/.*"latest"[^"]*"\([^"]*\)".*/\1/p'))"
    [[ -z "$ver" || "$ver" == "null" ]] && continue
    if [[ -z "$best" ]] || [[ "$(printf '%s\n%s\n' "$ver" "$best" | sort -V | tail -n1)" == "$ver" ]]; then
      best="$ver"
    fi
  done
  [[ -n "$best" ]] && { printf '%s' "$best"; return 0; }
  return 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -r|--region)    REGION="${2:-}"; shift 2;;
    -s|--stack)     STACK="${2:-}"; shift 2;;
    -t|--image-tag) TAG="${2:-}"; shift 2;;
    -h|--help) echo "Usage: upgrade.sh --region <aws-region> [--stack drishti] [--image-tag <ver>]"; exit 0;;
    *) echo "Unknown option: $1"; exit 1;;
  esac
done
[[ -z "$REGION" ]] && { echo "ERROR: --region is required."; exit 1; }

command -v aws >/dev/null 2>&1 || { echo "ERROR: AWS CLI not found. Run this in AWS CloudShell."; exit 1; }
aws sts get-caller-identity >/dev/null 2>&1 || { echo "ERROR: not signed in to AWS."; exit 1; }

if [[ -z "$TAG" ]]; then
  TAG="$(latest_version || true)"
  [[ -z "$TAG" ]] && { echo "ERROR: could not read the published version. Pass --image-tag <ver>."; exit 1; }
fi

ARN=$(aws apprunner list-services --region "$REGION" \
        --query "ServiceSummaryList[?ServiceName=='${STACK}-app'].ServiceArn" --output text)
[[ -z "$ARN" || "$ARN" == "None" ]] && { echo "ERROR: no App Runner service named '${STACK}-app' in $REGION."; exit 1; }

CURRENT=$(aws apprunner describe-service --region "$REGION" --service-arn "$ARN" \
            --query 'Service.SourceConfiguration.ImageRepository.ImageIdentifier' --output text)
echo "▶ Current image: $CURRENT"
echo "▶ Target image:  ${IMAGE_REPO}:${TAG}"
if [[ "$CURRENT" == "${IMAGE_REPO}:${TAG}" ]]; then
  echo "✅ Already on ${TAG} — nothing to do."
  exit 0
fi

# Update the image only. App Runner REPLACES the whole SourceConfiguration on update, so a
# hand-written one would silently wipe the runtime environment — the database URL, the OIDC
# client, the role name. Read the live configuration back and change exactly one field.
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required (it is preinstalled in CloudShell)."; exit 1; }
CONFIG=$(aws apprunner describe-service --region "$REGION" --service-arn "$ARN" \
           --query 'Service.SourceConfiguration' --output json)
UPDATED=$(printf '%s' "$CONFIG" | jq --arg img "${IMAGE_REPO}:${TAG}" \
            '.ImageRepository.ImageIdentifier = $img')

# Refuse to roll if the environment did not survive the edit — better a failed upgrade than a
# service that starts with no database credentials and drops straight out of health checks.
ENV_COUNT=$(printf '%s' "$UPDATED" | jq '[.ImageRepository.ImageConfiguration.RuntimeEnvironmentVariables // {} | length] | add')
if [[ "${ENV_COUNT:-0}" -lt 1 ]]; then
  echo "ERROR: could not read the service's runtime environment; refusing to update."
  exit 1
fi

aws apprunner update-service --region "$REGION" --service-arn "$ARN" \
  --source-configuration "$UPDATED" >/dev/null

echo "▶ Rolling… (App Runner replaces the container; the database is untouched)"
aws apprunner wait service-updated --region "$REGION" --service-arn "$ARN" 2>/dev/null || true

URL=$(aws apprunner describe-service --region "$REGION" --service-arn "$ARN" \
        --query 'Service.ServiceUrl' --output text)
cat <<EOF

✅ Drishti upgraded to ${TAG}.

   Open: https://${URL}
   Your attestations, decisions and report branding are intact — the schema migrates on boot.
   The last scan is restored from the database; re-scan for fresh results.
EOF
